spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

app.datasource.primary.url=jdbc:h2:mem:testdb
app.datasource.primary.driver-class-name=org.h2.Driver
app.datasource.primary.username=sa
app.datasource.primary.password=password
app.datasource.audit.url=jdbc:h2:mem:auditdb
app.datasource.audit.driver-class-name=org.h2.Driver
app.datasource.audit.username=sa
app.datasource.audit.password=password
